server: true
auto: true
pygments: true
permalink: ./:title
source: .
destination: ./_site
plugins: ./_plugins
markdown: maruku
    
embedly:
  api_key: 5e7a32eee2cd11e09ee04040d3dc5c07

  flickr:
    maxwidth: 600

  vimeo:
    width: 600

